# This is the configuration used to check the rubocop source code.

AllCops:
  Include:
    - Gemfile
    - Rakefile
  Exclude:
    - files/default/rmate
    - spec/foodcritic/**/*

EmptyLines:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

SingleSpaceBeforeFirstArg:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/CommentIndentation:
  Enabled: false
